[tool.poetry]
name = "timeseries-bootcamp"
version = "0.1.0"
description = "Tutorial timeseries predictions"
authors = ["aleksey <kvyatkovsky89@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pandas = "^2.2.3"
matplotlib = "^3.10.0"
jupyter = "^1.1.1"
scikit-learn = "^1.6.1"


[tool.poetry.group.dev.dependencies]
black = "^25.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
